// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

/// One playlist generated by ListenBrainz Radio.
public struct LBGeneratedRadio: Sendable {
    public let title: String?
    public let annotation: String?
    public let tracks: [LBPlaylistTrack]
    public let feedback: [String]

    public init(
        title: String?,
        annotation: String?,
        tracks: [LBPlaylistTrack],
        feedback: [String]
    ) {
        self.title = title
        self.annotation = annotation
        self.tracks = tracks
        self.feedback = feedback
    }

    init(raw: RawGeneratedRadioResponse) {
        title = raw.payload.jspf.playlist.title
        annotation = raw.payload.jspf.playlist.annotation
        tracks = raw.payload.jspf.playlist.tracks.map(LBPlaylistTrack.init)
        feedback = raw.payload.feedback
    }
}
